CREATE TYPE state AS ENUM ('track','untrack');
create table if not exists Chats
(
    telegram_id bigint primary key,
    status      state not null
);
create table if not exists Links
(
    id      int primary key generated by default as identity,
    url     varchar not null,
    chat_id bigint references Chats (telegram_id)
)

