app:
  git-hub-base-url: https://api.github.com/
  stack-overflow-base-url: https://api.stackexchange.com/2.3/
  scheduler:
    enable: false
    interval: 10s

spring:
  application:
    name: scrapper

springdoc:
  api-docs:
    path: /swagger-ui
server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
