app:
  git-hub-base-url: https://api.github.com/
  stack-overflow-base-url: https://api.stackexchange.com/2.3/
  bot-base-url: http://localhost:8080/
  scheduler:
    enable: false
    interval: 10s

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: scrapper
  liquibase:
    change-log: migrations/master.xml
    enabled: false

springdoc:
  api-docs:
    path: /swagger-ui

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
