app:
  database-access-type: jdbc
  git-hub-base-url: http://localhost:8080/
  stack-overflow-base-url: http://localhost:8080/
  bot-base-url: http://localhost:8080/
  link-check-delay-in-hours: 2
  scheduler:
    enable: false
    interval: 10s

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: (/tg-chat.*)|(/links.*)
      strategy: first
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 10
              time: 60
              unit: seconds
              refill-speed: interval
          skip-condition: '@rateLimiterService.isSkipped(getRemoteAddr())'

rate-limiter:
  whitelist: ${WHITELISTED_IPS:localhost,127.0.0.1}

client:
  retry: constant
  initial-delay: 1000
  max-delay: 15000
  increment: 3000
  max-attempts: 2
  codes: 500,502,503,504

spring:
  cache:
    cache-names:
      - buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    type: none
  jpa.properties.hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: false
  datasource:
    url: jdbc:postgresql://localhost:5433/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: migrations/master.xml
    enabled: false
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
