app:
  git-hub-base-url: http://localhost:8080/
  stack-overflow-base-url: http://localhost:8080/
  bot-base-url: http://localhost:8090/
  scheduler:
    enable: false
    interval: 10s

spring:
  liquibase:
    change-log: migrations/master.xml
    enabled: false
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
