app:
  telegram-token:

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username: postgres
    password: root

  jpa.properties.hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
